import 'package:vivacissimo/models/models.dart';

Map<String, Artist> dummyArtists = {
  "YOASOBI": Artist(
    name: "YOASOBI",
    id: "df6c619f-4334-43e2-8b6a-4a32af1e4f85",
    tags: {},
    sortName: "YOASOBI",
    type: ArtistType.group,
    description: null,
  ),
  "Ado": Artist(
    name: "Ado",
    id: "e134b52f-2e9e-4734-9bc3-bea9648d1fa1",
    tags: {},
    sortName: "Ado",
    type: ArtistType.person,
    description: "Japanese vocalist",
  ),
  "Amateras Records": Artist(
    name: "Amateras Records",
    id: "957b8dab-5a3a-47af-b7e7-e43cfd96eb62",
    tags: {},
    sortName: "Amateras Records",
    type: ArtistType.group,
    description: "Doujin circle",
  ),
  "DiGiTAL WiNG": Artist(
    name: "DiGiTAL WiNG",
    id: "a98c8c65-fe7a-47b4-8074-434d15a9f5b0",
    tags: {},
    sortName: "DiGiTAL WiNG",
    type: ArtistType.group,
    description: "Doujin circle",
  ),
  "Camellia": Artist(
    name: "かめりあ",
    id: "151bb385-1af0-40b6-9269-bf2ed982311f",
    tags: {},
    sortName: "Camellia",
    type: ArtistType.person,
    description: "Camellia, Japanese DJ/producer",
  ),
  "Fujii Kaze": Artist(
    name: "藤井風",
    id: "c3a4aeca-8f02-4d22-b1ff-693434ab09a8",
    tags: {},
    sortName: "Fujii, Kaze",
    type: ArtistType.person,
    description: "Fujii Kaze",
  ),
  "imase": Artist(
    name: "imase",
    id: "bc83173f-c86f-4343-b3e7-aad839a47a54",
    tags: {},
    sortName: "imase",
    type: ArtistType.person,
    description: "",
  ),
  "Kikuo": Artist(
    name: "きくお",
    id: "23987750-a64d-4241-a147-2213890464a2",
    tags: {},
    sortName: "kikuo",
    type: ArtistType.person,
    description: "Kikuo, Vocaloid producer",
  ),
  "Kento": Artist(
    name: "こっちのけんと",
    id: "f0d4005f-e138-472b-97f6-02233375ad90",
    tags: {},
    sortName: "Kocchi no Kento",
    type: ArtistType.person,
    description: "Kocchi no Kento",
  ),
  "MAISINdes": Artist(
    name: "MAISONdes",
    id: "5005beb6-9da2-48ba-bfd9-aa8ddc6d0117",
    tags: {},
    sortName: "MAISONdes",
    type: ArtistType.group,
    description: "",
  ),
  "MYTH": Artist(
    name: "MYTH & ROID",
    id: "3ca85e1b-be9b-4b67-91eb-d0f54ff31177",
    tags: {},
    sortName: "MYTH & ROID",
    type: ArtistType.group,
    description: "",
  ),
  "Queen Bee": Artist(
    name: "女王蜂",
    id: "9b643375-2913-4877-bb1e-3de576ff20ab",
    tags: {},
    sortName: "Ziyoou, Vachi",
    type: ArtistType.group,
    description: "Ziyoou-Vachi, Queen Bee",
  ),
  "REOL": Artist(
    name: "REOL",
    id: "8852b087-c17d-4df5-9699-96d52cb31fc5",
    tags: {},
    sortName: "REOL",
    type: ArtistType.group,
    description: "Electronic trio",
  ),
  "Risa Yuzuki": Artist(
    name: "Risa Yuzuki",
    id: "2bbcc070-62f8-4669-b77c-fdaa2d7c3f4a",
    tags: {},
    sortName: "Yuzuki, Risa",
    type: ArtistType.person,
    description: "Singer, lyricist",
  ),
  "TUYU": Artist(
    name: "ツユ",
    id: "2b0a8be6-bfb8-4f62-b21d-f47a3104157e",
    tags: {},
    sortName: "TUYU",
    type: ArtistType.group,
    description: "TUYU",
  ),
  "void": Artist(
    name: "void",
    id: "c8a0cb7a-99c8-4bcd-82d5-bcef201e13d1",
    tags: {},
    sortName: "void",
    type: ArtistType.person,
    description: "Japanese, labels: Mournfinale, electro planet",
  ),
  "yama": Artist(
    name: "yama",
    id: "a3becc83-9dab-48c6-9513-e269e1e4c49a",
    tags: {},
    sortName: "yama",
    type: ArtistType.person,
    description: "Japanese singer",
  ),
  "BlackY": Artist(
    name: "BlackY",
    id: "30911991-7c9a-41a3-b447-6f582bfe561e",
    tags: {},
    sortName: "BlackY",
    type: ArtistType.person,
    description: "Japanese trance artist",
  ),
  "Yuta Imai": Artist(
    name: "Yuta Imai",
    id: 'b17e8126-7642-44a8-a311-6fb6546cf672',
    tags: {},
    type: ArtistType.person,
    sortName: "Yuta Imai",
  ),
};

void main() {
  dummyArtists.keys.forEach(print);
}
