import 'package:vivacissimo/models/models.dart';

import 'artists.dart';

Map<String, Release> dummyReleases = {
  "Yoru ni Kakeru": Release(
    title: "Yoru ni Kakeru",
    id: "2c5e887b-f5a3-4d8d-a94f-00dc98e0baa8",
    tags: {
      Tag(name: "J-Pop", value: "J-Pop", type: TagType.genre),
      Tag(name: "Pop", value: "Pop", type: TagType.subGenre),
      Tag(name: "Japanese", value: "Japanese", type: TagType.language),
      Tag(name: "Night", value: "Night", type: TagType.vibe),
      Tag(name: "Electronic", value: "Electronic", type: TagType.instruments),
      Tag(name: "Female vocals", value: "Female vocals", type: TagType.vocals),
      Tag(name: "Upbeat", value: "Upbeat", type: TagType.tempo),
      Tag(name: "Dance", value: "Dance", type: TagType.other),
      Tag(name: "YOASOBI", value: "YOASOBI", type: TagType.other),
      Tag(name: "Modern", value: "Modern", type: TagType.other),
      Tag(name: "Synth", value: "Synth", type: TagType.instruments),
      Tag(name: "Dreamy", value: "Dreamy", type: TagType.vibe),
      Tag(name: "Chart-topper", value: "Chart-topper", type: TagType.other),
      Tag(name: "Popular", value: "Popular", type: TagType.other),
      Tag(name: "Hit song", value: "Hit song", type: TagType.other),
    },
    credit: ArtistCredit(
      prefix: "",
      parts: [
        ArtistCreditPart(
          artist: dummyArtists["YOASOBI"]!,
          credit: null,
          joinPhrase: "",
        ),
      ],
    ),
  ),
  "Usseewa": Release(
    title: "Usseewa",
    id: "7b84990d-ffc8-442c-b900-839d1700b13b",
    tags: {
      Tag(name: "J-Pop", value: "J-Pop", type: TagType.genre),
      Tag(name: "Pop Rock", value: "Pop Rock", type: TagType.subGenre),
      Tag(name: "Japanese", value: "Japanese", type: TagType.language),
      Tag(name: "Angry", value: "Angry", type: TagType.vibe),
      Tag(name: "Energetic", value: "Energetic", type: TagType.vibe),
      Tag(name: "Fast", value: "Fast", type: TagType.tempo),
      Tag(name: "Female vocals", value: "Female vocals", type: TagType.vocals),
      Tag(name: "Guitar", value: "Guitar", type: TagType.instruments),
      Tag(name: "Bass", value: "Bass", type: TagType.instruments),
      Tag(name: "Drums", value: "Drums", type: TagType.instruments),
      Tag(name: "Hit song", value: "Hit song", type: TagType.other),
      Tag(name: "Popular", value: "Popular", type: TagType.other),
      Tag(name: "Modern", value: "Modern", type: TagType.other),
      Tag(name: "Iconic", value: "Iconic", type: TagType.other),
      Tag(name: "Catchy", value: "Catchy", type: TagType.vibe),
    },
    credit: ArtistCredit(
      prefix: "",
      parts: [
        ArtistCreditPart(
          artist: dummyArtists["Ado"]!,
          credit: null,
          joinPhrase: "",
        ),
      ],
    ),
  ),
  "Scarlet Moon": Release(
    title: "Scarlet Moon",
    id: "3f88374e-10bd-4fea-9a62-05c513289dce",
    tags: {
      Tag(name: "Electronic", value: "Electronic", type: TagType.genre),
      Tag(name: "Touhou", value: "Touhou", type: TagType.subGenre),
      Tag(name: "Japanese", value: "Japanese", type: TagType.language),
      Tag(name: "Energetic", value: "Energetic", type: TagType.vibe),
      Tag(name: "Fast", value: "Fast", type: TagType.tempo),
      Tag(name: "Synth", value: "Synth", type: TagType.instruments),
      Tag(name: "Club", value: "Club", type: TagType.vibe),
      Tag(name: "Dance", value: "Dance", type: TagType.other),
      Tag(name: "Remix", value: "Remix", type: TagType.other),
      Tag(name: "Popular", value: "Popular", type: TagType.other),
      Tag(name: "Piano", value: "Piano", type: TagType.instruments),
      Tag(name: "Vocals", value: "Vocals", type: TagType.vocals),
      Tag(name: "Gaming", value: "Gaming", type: TagType.other),
      Tag(name: "Modern", value: "Modern", type: TagType.other),
      Tag(name: "Iconic", value: "Iconic", type: TagType.other),
    },
    credit: ArtistCredit(
      prefix: "",
      parts: [
        ArtistCreditPart(
          artist: dummyArtists["Amateras Records"]!,
          credit: null,
          joinPhrase: "",
        ),
      ],
    ),
  ),
  "Into the Night": Release(
    title: "Into the Night",
    id: "f59934ac-e6f9-409e-96b9-576033f1c571",
    tags: {
      Tag(name: "J-Pop", value: "J-Pop", type: TagType.genre),
      Tag(name: "Pop", value: "Pop", type: TagType.subGenre),
      Tag(name: "Japanese", value: "Japanese", type: TagType.language),
      Tag(name: "Dreamy", value: "Dreamy", type: TagType.vibe),
      Tag(name: "Electronic", value: "Electronic", type: TagType.instruments),
      Tag(name: "Female vocals", value: "Female vocals", type: TagType.vocals),
      Tag(name: "Upbeat", value: "Upbeat", type: TagType.tempo),
      Tag(name: "Dance", value: "Dance", type: TagType.other),
      Tag(name: "YOASOBI", value: "YOASOBI", type: TagType.other),
      Tag(name: "Modern", value: "Modern", type: TagType.other),
      Tag(name: "Synth", value: "Synth", type: TagType.instruments),
      Tag(name: "Chart-topper", value: "Chart-topper", type: TagType.other),
      Tag(name: "Popular", value: "Popular", type: TagType.other),
      Tag(name: "Hit song", value: "Hit song", type: TagType.other),
      Tag(name: "Energetic", value: "Energetic", type: TagType.vibe),
    },
    credit: ArtistCredit(
      prefix: "",
      parts: [
        ArtistCreditPart(
          artist: dummyArtists["YOASOBI"]!,
          credit: null,
          joinPhrase: "",
        ),
      ],
    ),
  ),
  "New Genesis": Release(
    title: "New Genesis",
    id: "142187c0-3d44-4339-9c5e-a28aef08dd7f",
    tags: {
      Tag(name: "J-Pop", value: "J-Pop", type: TagType.genre),
      Tag(name: "Anime", value: "Anime", type: TagType.subGenre),
      Tag(name: "Japanese", value: "Japanese", type: TagType.language),
      Tag(name: "Epic", value: "Epic", type: TagType.vibe),
      Tag(name: "Dynamic", value: "Dynamic", type: TagType.tempo),
      Tag(name: "Female vocals", value: "Female vocals", type: TagType.vocals),
      Tag(name: "Energetic", value: "Energetic", type: TagType.vibe),
      Tag(name: "Ado", value: "Ado", type: TagType.other),
      Tag(name: "Hit song", value: "Hit song", type: TagType.other),
      Tag(name: "Popular", value: "Popular", type: TagType.other),
      Tag(name: "Modern", value: "Modern", type: TagType.other),
      Tag(name: "Guitar", value: "Guitar", type: TagType.instruments),
      Tag(name: "Bass", value: "Bass", type: TagType.instruments),
      Tag(name: "Powerful", value: "Powerful", type: TagType.vibe),
      Tag(name: "Catchy", value: "Catchy", type: TagType.other),
    },
    credit: ArtistCredit(
      prefix: "",
      parts: [
        ArtistCreditPart(
          artist: dummyArtists["Ado"]!,
          credit: null,
          joinPhrase: "",
        ),
      ],
    ),
  ),
  "Crimson Night": Release(
    title: "Crimson Night",
    id: "d11168cd-b49d-418a-b18f-1c999a7c6cca",
    tags: {
      Tag(name: "Electronic", value: "Electronic", type: TagType.genre),
      Tag(name: "Touhou", value: "Touhou", type: TagType.subGenre),
      Tag(name: "Japanese", value: "Japanese", type: TagType.language),
      Tag(name: "Energetic", value: "Energetic", type: TagType.vibe),
      Tag(name: "Fast", value: "Fast", type: TagType.tempo),
      Tag(name: "Synth", value: "Synth", type: TagType.instruments),
      Tag(name: "Club", value: "Club", type: TagType.vibe),
      Tag(name: "Dance", value: "Dance", type: TagType.other),
      Tag(name: "Remix", value: "Remix", type: TagType.other),
      Tag(name: "Piano", value: "Piano", type: TagType.instruments),
      Tag(name: "Vocals", value: "Vocals", type: TagType.vocals),
      Tag(name: "Gaming", value: "Gaming", type: TagType.other),
      Tag(name: "Modern", value: "Modern", type: TagType.other),
      Tag(name: "Iconic", value: "Iconic", type: TagType.other),
      Tag(name: "Catchy", value: "Catchy", type: TagType.other),
    },
    credit: ArtistCredit(
      prefix: "",
      parts: [
        ArtistCreditPart(
          artist: dummyArtists["Amateras Records"]!,
          credit: null,
          joinPhrase: "",
        ),
      ],
    ),
  ),
  "Senbonzakura": Release(
    title: "Senbonzakura",
    id: "6b1a7e77-27f8-4094-9f77-e31ff7d6f20b",
    tags: {
      Tag(name: "Vocaloid", value: "Vocaloid", type: TagType.genre),
      Tag(name: "J-Pop", value: "J-Pop", type: TagType.subGenre),
      Tag(name: "Japanese", value: "Japanese", type: TagType.language),
      Tag(name: "Traditional", value: "Traditional", type: TagType.vibe),
      Tag(name: "Energetic", value: "Energetic", type: TagType.vibe),
      Tag(name: "Fast", value: "Fast", type: TagType.tempo),
      Tag(name: "Catchy", value: "Catchy", type: TagType.other),
      Tag(name: "Iconic", value: "Iconic", type: TagType.other),
      Tag(name: "Hit song", value: "Hit song", type: TagType.other),
      Tag(name: "Popular", value: "Popular", type: TagType.other),
      Tag(name: "Guitar", value: "Guitar", type: TagType.instruments),
      Tag(name: "Bass", value: "Bass", type: TagType.instruments),
      Tag(name: "Piano", value: "Piano", type: TagType.instruments),
      Tag(name: "Powerful", value: "Powerful", type: TagType.vibe),
      Tag(name: "Modern", value: "Modern", type: TagType.other),
    },
    credit: ArtistCredit(
      prefix: "",
      parts: [
        ArtistCreditPart(
          artist: dummyArtists["Kikuo"]!,
          credit: null,
          joinPhrase: "",
        ),
      ],
    ),
  ),
  "Shangri-La": Release(
    title: "Shangri-La",
    id: "216e4101-de78-4251-b3e5-a73d1c76543b",
    tags: {
      Tag(name: "J-Pop", value: "J-Pop", type: TagType.genre),
      Tag(name: "Pop", value: "Pop", type: TagType.subGenre),
      Tag(name: "Japanese", value: "Japanese", type: TagType.language),
      Tag(name: "Dreamy", value: "Dreamy", type: TagType.vibe),
      Tag(name: "Electronic", value: "Electronic", type: TagType.instruments),
      Tag(name: "Male vocals", value: "Male vocals", type: TagType.vocals),
      Tag(name: "Upbeat", value: "Upbeat", type: TagType.tempo),
      Tag(name: "Dance", value: "Dance", type: TagType.other),
      Tag(name: "Fujii Kaze", value: "Fujii Kaze", type: TagType.other),
      Tag(name: "Modern", value: "Modern", type: TagType.other),
      Tag(name: "Synth", value: "Synth", type: TagType.instruments),
      Tag(name: "Chart-topper", value: "Chart-topper", type: TagType.other),
      Tag(name: "Popular", value: "Popular", type: TagType.other),
      Tag(name: "Hit song", value: "Hit song", type: TagType.other),
      Tag(name: "Energetic", value: "Energetic", type: TagType.vibe),
    },
    credit: ArtistCredit(
      prefix: "",
      parts: [
        ArtistCreditPart(
          artist: dummyArtists["Fujii Kaze"]!,
          credit: null,
          joinPhrase: "",
        ),
      ],
    ),
  ),
  "UNDEAD": Release(
    title: "UNDEAD",
    id: "6ef64156-143a-4fa5-ba81-9477500d4d3d",
    tags: {
      Tag(name: "J-Pop", value: "J-Pop", type: TagType.genre),
      Tag(name: "Pop", value: "Pop", type: TagType.subGenre),
      Tag(name: "Japanese", value: "Japanese", type: TagType.language),
      Tag(name: "Energetic", value: "Energetic", type: TagType.vibe),
      Tag(name: "Dynamic", value: "Dynamic", type: TagType.vibe),
      Tag(name: "Catchy", value: "Catchy", type: TagType.other),
      Tag(name: "Vocals", value: "Vocals", type: TagType.vocals),
      Tag(name: "Chart-topper", value: "Chart-topper", type: TagType.other),
      Tag(name: "Hit song", value: "Hit song", type: TagType.other),
      Tag(name: "Funky", value: "Funky", type: TagType.vibe),
      Tag(name: "Modern", value: "Modern", type: TagType.other),
      Tag(name: "Electronic", value: "Electronic", type: TagType.instruments),
      Tag(name: "YOASOBI", value: "YOASOBI", type: TagType.other),
    },
    credit: ArtistCredit(
      prefix: "",
      parts: [
        ArtistCreditPart(
          artist: dummyArtists["YOASOBI"]!,
          credit: null,
          joinPhrase: "",
        ),
      ],
    ),
  ),
  "Idol": Release(
    title: "Idol",
    id: "9ee0908a-11ff-4536-9bb9-e69a3b893d27",
    tags: {
      Tag(name: "J-Pop", value: "J-Pop", type: TagType.genre),
      Tag(name: "Pop", value: "Pop", type: TagType.subGenre),
      Tag(name: "Japanese", value: "Japanese", type: TagType.language),
      Tag(name: "Catchy", value: "Catchy", type: TagType.other),
      Tag(name: "Dance", value: "Dance", type: TagType.other),
      Tag(name: "Energetic", value: "Energetic", type: TagType.vibe),
      Tag(name: "Fast", value: "Fast", type: TagType.tempo),
      Tag(name: "Modern", value: "Modern", type: TagType.other),
      Tag(name: "Hit song", value: "Hit song", type: TagType.other),
      Tag(name: "Popular", value: "Popular", type: TagType.other),
      Tag(name: "YOASOBI", value: "YOASOBI", type: TagType.other),
      Tag(name: "Dynamic", value: "Dynamic", type: TagType.vibe),
      Tag(name: "Powerful", value: "Powerful", type: TagType.vibe),
      Tag(name: "Vocals", value: "Vocals", type: TagType.vocals),
    },
    credit: ArtistCredit(
      prefix: "",
      parts: [
        ArtistCreditPart(
          artist: dummyArtists["YOASOBI"]!,
          credit: null,
          joinPhrase: "",
        ),
      ],
    ),
  ),
  "NIGHT DANCER": Release(
    title: "NIGHT DANCER",
    id: "226901bc-be8a-4628-adf9-30f0d74acbbf",
    tags: {
      Tag(name: "J-Pop", value: "J-Pop", type: TagType.genre),
      Tag(name: "Pop", value: "Pop", type: TagType.subGenre),
      Tag(name: "Japanese", value: "Japanese", type: TagType.language),
      Tag(name: "Catchy", value: "Catchy", type: TagType.other),
      Tag(name: "Dance", value: "Dance", type: TagType.other),
      Tag(name: "Energetic", value: "Energetic", type: TagType.vibe),
      Tag(name: "Fast", value: "Fast", type: TagType.tempo),
      Tag(name: "Modern", value: "Modern", type: TagType.other),
      Tag(name: "Hit song", value: "Hit song", type: TagType.other),
      Tag(name: "Popular", value: "Popular", type: TagType.other),
      Tag(name: "imase", value: "imase", type: TagType.other),
      Tag(name: "Dynamic", value: "Dynamic", type: TagType.vibe),
      Tag(name: "Funky", value: "Funky", type: TagType.vibe),
      Tag(name: "Vocals", value: "Vocals", type: TagType.vocals),
    },
    credit: ArtistCredit(
      prefix: "",
      parts: [
        ArtistCreditPart(
          artist: dummyArtists["imase"]!,
          credit: null,
          joinPhrase: "",
        ),
      ],
    ),
  ),
  "Infinity Blossom feat. sea tsukiyama": Release(
    title: "Infinity Blossom feat. sea tsukiyama",
    id: "6a9440a5-019c-40cd-90e9-d3b3d8cc0ff3",
    tags: {
      Tag(name: "Electronic", value: "Electronic", type: TagType.genre),
      Tag(name: "Touhou", value: "Touhou", type: TagType.subGenre),
      Tag(name: "Japanese", value: "Japanese", type: TagType.language),
      Tag(name: "Catchy", value: "Catchy", type: TagType.other),
      Tag(name: "Club", value: "Club", type: TagType.vibe),
      Tag(name: "Energetic", value: "Energetic", type: TagType.vibe),
      Tag(name: "Fast", value: "Fast", type: TagType.tempo),
      Tag(name: "Modern", value: "Modern", type: TagType.other),
      Tag(name: "Hit song", value: "Hit song", type: TagType.other),
      Tag(name: "Popular", value: "Popular", type: TagType.other),
      Tag(
          name: "Amateras Records",
          value: "Amateras Records",
          type: TagType.other),
      Tag(name: "Synth", value: "Synth", type: TagType.instruments),
      Tag(name: "Vocals", value: "Vocals", type: TagType.vocals),
      Tag(name: "Dreamy", value: "Dreamy", type: TagType.vibe),
      Tag(name: "Gaming", value: "Gaming", type: TagType.other),
    },
    credit: ArtistCredit(
      prefix: "",
      parts: [
        ArtistCreditPart(
          artist: dummyArtists["Amateras Records"]!,
          credit: null,
          joinPhrase: "",
        ),
      ],
    ),
  ),
  "Stray Star feat. nayuta": Release(
    title: "Stray Star feat. nayuta",
    id: "fc906d76-f4d7-4b73-b742-f76a8de7e110",
    tags: {
      Tag(name: "Electronic", value: "Electronic", type: TagType.genre),
      Tag(name: "Touhou", value: "Touhou", type: TagType.subGenre),
      Tag(name: "Japanese", value: "Japanese", type: TagType.language),
      Tag(name: "Dreamy", value: "Dreamy", type: TagType.vibe),
      Tag(name: "Synth", value: "Synth", type: TagType.instruments),
      Tag(name: "Energetic", value: "Energetic", type: TagType.vibe),
      Tag(name: "Modern", value: "Modern", type: TagType.other),
      Tag(name: "Gaming", value: "Gaming", type: TagType.other),
      Tag(name: "Catchy", value: "Catchy", type: TagType.other),
      Tag(name: "Club", value: "Club", type: TagType.vibe),
      Tag(name: "Dance", value: "Dance", type: TagType.other),
      Tag(name: "Fast", value: "Fast", type: TagType.tempo),
      Tag(name: "Vocals", value: "Vocals", type: TagType.vocals),
      Tag(
          name: "Amateras Records",
          value: "Amateras Records",
          type: TagType.other),
    },
    credit: ArtistCredit(
      prefix: "",
      parts: [
        ArtistCreditPart(
          artist: dummyArtists["Amateras Records"]!,
          credit: null,
          joinPhrase: "",
        ),
      ],
    ),
  ),
  "Trapped in the Past": Release(
    title: "Trapped in the Past",
    id: "2ff9d50d-bea2-4907-a008-406b4a083028",
    tags: {
      Tag(name: "Indie", value: "Indie", type: TagType.genre),
      Tag(name: "Pop", value: "Pop", type: TagType.subGenre),
      Tag(name: "Japanese", value: "Japanese", type: TagType.language),
      Tag(name: "Melancholic", value: "Melancholic", type: TagType.vibe),
      Tag(name: "Emotional", value: "Emotional", type: TagType.vibe),
      Tag(name: "Piano", value: "Piano", type: TagType.instruments),
      Tag(name: "Vocals", value: "Vocals", type: TagType.vocals),
      Tag(name: "Slow", value: "Slow", type: TagType.tempo),
      Tag(name: "Deep", value: "Deep", type: TagType.vibe),
      Tag(name: "TUYU", value: "TUYU", type: TagType.other),
      Tag(name: "Touching", value: "Touching", type: TagType.vibe),
      Tag(name: "Hit song", value: "Hit song", type: TagType.other),
      Tag(name: "Authentic", value: "Authentic", type: TagType.other),
      Tag(name: "Harmonic", value: "Harmonic", type: TagType.other),
    },
    credit: ArtistCredit(
      prefix: "",
      parts: [
        ArtistCreditPart(
          artist: dummyArtists["TUYU"]!,
          credit: null,
          joinPhrase: "",
        ),
      ],
    ),
  ),
  "Hide and Seek Alone": Release(
    title: "Hide and Seek Alone",
    id: "03152b98-b9b5-48ac-b673-a1e8f3866d69",
    tags: {
      Tag(name: "Indie", value: "Indie", type: TagType.genre),
      Tag(name: "Pop", value: "Pop", type: TagType.subGenre),
      Tag(name: "Japanese", value: "Japanese", type: TagType.language),
      Tag(name: "Dark", value: "Dark", type: TagType.vibe),
      Tag(name: "Piano", value: "Piano", type: TagType.instruments),
      Tag(name: "Vocals", value: "Vocals", type: TagType.vocals),
      Tag(name: "Slow", value: "Slow", type: TagType.tempo),
      Tag(name: "Melancholic", value: "Melancholic", type: TagType.vibe),
      Tag(name: "Deep", value: "Deep", type: TagType.vibe),
      Tag(name: "Emotional", value: "Emotional", type: TagType.vibe),
      Tag(name: "TUYU", value: "TUYU", type: TagType.other),
      Tag(name: "Harmonic", value: "Harmonic", type: TagType.other),
      Tag(name: "Touching", value: "Touching", type: TagType.vibe),
      Tag(name: "Authentic", value: "Authentic", type: TagType.other),
    },
    credit: ArtistCredit(
      prefix: "",
      parts: [
        ArtistCreditPart(
          artist: dummyArtists["TUYU"]!,
          credit: null,
          joinPhrase: "",
        ),
      ],
    ),
  ),
  "Ego Eimi": Release(
    title: "Ego Eimi",
    id: "13b74206-42b6-4709-94bf-2789a9921506",
    tags: {
      Tag(name: "Electronic", value: "Electronic", type: TagType.genre),
      Tag(name: "Vocaloid", value: "Vocaloid", type: TagType.subGenre),
      Tag(name: "Japanese", value: "Japanese", type: TagType.language),
      Tag(name: "Dreamy", value: "Dreamy", type: TagType.vibe),
      Tag(name: "Synth", value: "Synth", type: TagType.instruments),
      Tag(name: "Vocals", value: "Vocals", type: TagType.vocals),
      Tag(name: "Modern", value: "Modern", type: TagType.other),
      Tag(name: "Catchy", value: "Catchy", type: TagType.other),
      Tag(name: "Club", value: "Club", type: TagType.vibe),
      Tag(name: "Dance", value: "Dance", type: TagType.other),
      Tag(name: "Fast", value: "Fast", type: TagType.tempo),
      Tag(name: "Remix", value: "Remix", type: TagType.other),
      Tag(name: "Gaming", value: "Gaming", type: TagType.other),
      Tag(name: "Energetic", value: "Energetic", type: TagType.vibe),
      Tag(name: "Risa Yuzuki", value: "Risa Yuzuki", type: TagType.other),
    },
    credit: ArtistCredit(
      prefix: "",
      parts: [
        ArtistCreditPart(
          artist: dummyArtists["Risa Yuzuki"]!,
          credit: null,
          joinPhrase: " & ",
        ),
        ArtistCreditPart(
          artist: dummyArtists["BlackY"]!,
          credit: null,
          joinPhrase: "",
        ),
      ],
    ),
  ),
  "ALTER EGO": Release(
    title: "ALTER EGO",
    id: "",
    tags: {
      Tag(name: "Electronic", value: "Electronic", type: TagType.genre),
      Tag(name: "J-Core", value: "J-Core", type: TagType.subGenre),
      Tag(name: "Japanese", value: "Japanese", type: TagType.language),
      Tag(name: "Energetic", value: "Energetic", type: TagType.vibe),
      Tag(name: "Synth", value: "Synth", type: TagType.instruments),
      Tag(name: "Fast", value: "Fast", type: TagType.tempo),
      Tag(name: "Dynamic", value: "Dynamic", type: TagType.vibe),
      Tag(name: "Modern", value: "Modern", type: TagType.other),
      Tag(name: "Gaming", value: "Gaming", type: TagType.other),
      Tag(name: "Catchy", value: "Catchy", type: TagType.other),
      Tag(name: "Club", value: "Club", type: TagType.vibe),
      Tag(name: "Dance", value: "Dance", type: TagType.other),
      Tag(name: "Powerful", value: "Powerful", type: TagType.vibe),
      Tag(name: "Hit song", value: "Hit song", type: TagType.other),
      Tag(name: "Yuta Imai", value: "Yuta Imai", type: TagType.other),
      Tag(name: "Qlarabelle", value: "Qlarabelle", type: TagType.other),
    },
    credit: ArtistCredit(
      prefix: "",
      parts: [
        ArtistCreditPart(
          artist: dummyArtists["Yuta Imai"]!,
          credit: null,
          joinPhrase: " vs ",
        ),
        ArtistCreditPart(
          artist: dummyArtists["Yuta Imai"]!,
          credit: "Qlarabelle",
          joinPhrase: "",
        ),
      ],
    ),
  ),
};
