name: vivacissimo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.0
  uuid: ^4.5.1

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  file_picker: ^8.1.6
  http: ^1.2.2
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
  - .env
  - assets/
  - assets/dummy/
